import numpy as np
import pytest

from regime.hmm import GaussianHMM


def make_two_regime_data(n_per_regime=150, seed=0):
    """
    Synthetic 2-state data with well-separated Gaussian clusters in 2D,
    generated by an actual Markov chain with sticky transitions (so the
    HMM's temporal structure is meaningfully exercised, not just i.i.d.
    cluster membership).
    """
    rng = np.random.default_rng(seed)
    true_means = np.array([[-1.0, -1.0], [1.0, 1.0]])
    true_std = 0.3

    T = n_per_regime * 2
    states = np.zeros(T, dtype=int)
    states[0] = rng.integers(0, 2)
    stay_prob = 0.95
    for t in range(1, T):
        if rng.random() < stay_prob:
            states[t] = states[t - 1]
        else:
            states[t] = 1 - states[t - 1]

    X = np.array([rng.normal(true_means[s], true_std) for s in states])
    return X, states, true_means


# --------------------------------------------------------------------- #
# Emission model
# --------------------------------------------------------------------- #


def test_emission_probs_sum_is_positive_and_finite():
    hmm = GaussianHMM(n_states=3, n_features=2, random_seed=1)
    x = np.array([0.1, -0.2])
    probs = hmm.emission_probs(x)
    assert len(probs) == 3
    assert np.all(np.isfinite(probs))
    assert np.all(probs >= 0)


def test_emission_probs_highest_for_nearest_mean():
    hmm = GaussianHMM(n_states=2, n_features=1, random_seed=1)
    hmm.means = np.array([[0.0], [10.0]])
    hmm.variances = np.array([[1.0], [1.0]])
    probs = hmm.emission_probs(np.array([0.1]))
    assert probs[0] > probs[1]


def test_emission_probs_no_underflow_on_extreme_values_with_small_variance():
    hmm = GaussianHMM(n_states=2, n_features=4, min_variance=1e-3, random_seed=1)
    hmm.means = np.zeros((2, 4))
    hmm.variances = np.full((2, 4), 1e-3)
    x = np.array([1.0, -1.0, 1.0, -1.0])
    probs = hmm.emission_probs(x)
    assert np.isclose(np.max(probs), 1.0)
    assert np.all(np.isfinite(probs))


# --------------------------------------------------------------------- #
# Forward-backward / filtering
# --------------------------------------------------------------------- #


def test_forward_filter_probabilities_sum_to_one_each_timestep():
    X, _, _ = make_two_regime_data()
    hmm = GaussianHMM(n_states=2, n_features=2, random_seed=1)
    hmm.fit(X, max_iterations=20)
    filtered = hmm.forward_filter(X)
    sums = filtered.sum(axis=1)
    np.testing.assert_allclose(sums, np.ones(len(X)), atol=1e-8)


def test_smoothed_posteriors_sum_to_one_each_timestep():
    X, _, _ = make_two_regime_data()
    hmm = GaussianHMM(n_states=2, n_features=2, random_seed=1)
    hmm.fit(X, max_iterations=20)
    gamma = hmm.smoothed_posteriors(X)
    sums = gamma.sum(axis=1)
    np.testing.assert_allclose(sums, np.ones(len(X)), atol=1e-8)


def test_forward_step_matches_batch_forward_filter():
    """
    The whole point of forward_step: replaying observations one at a time
    via the incremental update must produce identical filtered
    probabilities to the batch forward pass over the same sequence.
    """
    X, _, _ = make_two_regime_data()
    hmm = GaussianHMM(n_states=2, n_features=2, random_seed=1)
    hmm.fit(X, max_iterations=20)

    batch_filtered = hmm.forward_filter(X)

    alpha = None
    streamed = []
    for t in range(len(X)):
        alpha, _ = hmm.forward_step(alpha, X[t])
        streamed.append(alpha)
    streamed = np.array(streamed)

    np.testing.assert_allclose(streamed, batch_filtered, atol=1e-8)


# --------------------------------------------------------------------- #
# Baum-Welch (EM) training
# --------------------------------------------------------------------- #


def test_log_likelihood_monotonically_nondecreasing_during_em():
    X, _, _ = make_two_regime_data()
    hmm = GaussianHMM(n_states=2, n_features=2, random_seed=3)
    hmm.fit(X, max_iterations=50, tolerance=1e-10)

    history = hmm.log_likelihood_history
    assert len(history) >= 2
    diffs = np.diff(history)
    assert np.all(diffs > -1e-6), f"log-likelihood decreased: {history}"


def test_fit_recovers_approximate_cluster_means():
    X, _, true_means = make_two_regime_data(n_per_regime=300, seed=5)
    hmm = GaussianHMM(n_states=2, n_features=2, random_seed=7)
    hmm.fit(X, max_iterations=100)

    fitted = hmm.means
    dist_00 = np.linalg.norm(fitted[0] - true_means[0])
    dist_01 = np.linalg.norm(fitted[0] - true_means[1])
    if dist_00 < dist_01:
        pairing = [0, 1]
    else:
        pairing = [1, 0]
    for i, true_idx in enumerate(pairing):
        assert np.linalg.norm(fitted[i] - true_means[true_idx]) < 0.3


def test_fit_raises_on_insufficient_data():
    hmm = GaussianHMM(n_states=4, n_features=2, random_seed=1)
    X = np.random.default_rng(0).normal(0, 1, size=(3, 2))
    with pytest.raises(ValueError, match="at least"):
        hmm.fit(X)


def test_fit_raises_on_wrong_feature_dimensionality():
    hmm = GaussianHMM(n_states=2, n_features=3, random_seed=1)
    X = np.random.default_rng(0).normal(0, 1, size=(20, 2))
    with pytest.raises(ValueError, match="shape"):
        hmm.fit(X)


def test_transition_matrix_rows_sum_to_one_after_fit():
    X, _, _ = make_two_regime_data()
    hmm = GaussianHMM(n_states=2, n_features=2, random_seed=1)
    hmm.fit(X, max_iterations=20)
    row_sums = hmm.A.sum(axis=1)
    np.testing.assert_allclose(row_sums, np.ones(2), atol=1e-8)


def test_variances_floored_at_min_variance():
    X, _, _ = make_two_regime_data()
    hmm = GaussianHMM(n_states=2, n_features=2, min_variance=0.05, random_seed=1)
    hmm.fit(X, max_iterations=20)
    assert np.all(hmm.variances >= 0.05 - 1e-9)


# --------------------------------------------------------------------- #
# Viterbi
# --------------------------------------------------------------------- #


def test_viterbi_recovers_dominant_state_structure():
    X, true_states, _ = make_two_regime_data(n_per_regime=300, seed=9)
    hmm = GaussianHMM(n_states=2, n_features=2, random_seed=1)
    hmm.fit(X, max_iterations=100)
    path = hmm.viterbi(X)

    agreement_direct = np.mean(path == true_states)
    agreement_flipped = np.mean(path == (1 - true_states))
    assert max(agreement_direct, agreement_flipped) > 0.85


def test_viterbi_returns_valid_state_indices():
    X, _, _ = make_two_regime_data()
    hmm = GaussianHMM(n_states=2, n_features=2, random_seed=1)
    hmm.fit(X, max_iterations=20)
    path = hmm.viterbi(X)
    assert path.min() >= 0
    assert path.max() < hmm.n_states
    assert len(path) == len(X)


# --------------------------------------------------------------------- #
# Constructor validation
# --------------------------------------------------------------------- #


def test_constructor_rejects_too_few_states():
    with pytest.raises(ValueError):
        GaussianHMM(n_states=1, n_features=2)


def test_constructor_rejects_zero_features():
    with pytest.raises(ValueError):
        GaussianHMM(n_states=2, n_features=0)
